services:
  db:
    image: mysql:latest
    container_name: ScrumExtreme
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: kingmalik
      MYSQL_DATABASE: scrumextreme
    volumes:
      - scrumextreme_mysql_data:/var/lib/mysql

volumes:
  scrumextreme_mysql_data:
